version: '2'
services:
    web:
        build: .
        ports:
            - "5055:5055"
            - "5004:5005"
        depends_on:
            - redis
        restart: always
    redis:
        image: redis
        restart: always

